services:
  app:
    image: rsomonte/taskerbot:latest
    env_file: .env
    container_name: taskerbot_app
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
    ports:
      - "3000:3000"